config/routes.rb
AjoCms::Engine.routes.draw do
	root :to => "sections#index"
	match '../', :to => "ajo_cms/views#index", :as => :rails_app_root
	resources :users do
		get :first_user, :on => :collection
	end
	resources :sessions, :only => [:new, :create]
	match 'logout' => 'sessions#destroy', :as => 'logout'
	resources :companies
	resources :sections do
		collection { post :sort }
		resources :pages do
			collection { post :sort }
			resources :subsections do
				collection { post :sort }
				resources :posts do
					collection { post :sort }
				end
			end
		end
	end
	Rails.application.routes.draw do
		root :to => "ajo_cms/views#index"
		match '/:section_name/:page_name', :to => 'ajo_cms/views#section'
		match '/:section_name/:page_name/:post_id', :to => 'ajo_cms/views#post'
		match '/:section_name', :to => 'ajo_cms/views#section'
	end
	
end

app/models/ajo_cms/post.rb
module AjoCms
  class Post < ActiveRecord::Base
  	attr_accessible :title, :content, :post_type, :subsection_id, :image, :file, :date, :crop_x, :crop_y, :crop_w, :crop_h

  	default_scope order('position ASC')

  	belongs_to :subsection
  	mount_uploader :image, ImageUploader
  	mount_uploader :file, FileUploader
    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    after_update :crop_image


    def crop_image
      image.recreate_versions! if crop_x.present?
    end

	  def next
	  	self.class.find(:first, :conditions => ["id > ? And subsection_id = ?", self.id, self.subsection_id])
	  end

	  def last
	  	self.class.find(:first, :conditions => ["id < ? And subsection_id = ?", self.id, self.subsection_id])
	  end
  end
end

app/controllers/ajo_cms/posts_controller.rb
module AjoCms
  class PostsController < ApplicationController
  	layout 'ajo_cms/admin'
    before_filter :set_defaults

    def set_defaults
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @sections = Section.all
    end
  	def new
  		@post = Post.new
  	end

    def edit
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @post = Post.find(params[:id])
    end

    def show
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @posts = @page.posts
      @post = Post.find(params[:id])
      @sliders = @page.posts.where(:post_type => 'slider')
      @headlines = @page.posts.where(:post_type => 'headlines')
      @blogs = @page.posts.where(:post_type => 'blogs')
      @images = @page.posts.where(:post_type => 'gallery')
    end


  	def create
      @sections = Section.all
  		@post = Post.new(params[:post])

  		if @post.save
        if params[:post][:image].present? && (params[:post][:post_type] == 'slider' || params[:post][:post_type == 'text'])
          render :crop
        else
          redirect_to section_page_path(params[:section_id], params[:page_id]), notice: 'Post created!'
        end
  		else
  			render 'new'
  		end
  	end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params[:post])
        redirect_to section_page_path(params[:section_id], params[:page_id], notice: 'Post updated!')
      else
        render 'edit'
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy()

      redirect_to section_page_path(params[:section_id], params[:page_id])
    end
  end
end

app/helpers/ajo_cms/posts_helper.rb
module AjoCms
  module PostsHelper
  end
end

app/views/layouts/posts/_gallery.html.haml
.row
	.span3
		.thumbnail= image_tag "ajo_cms/page_#{@page.layout}.png"
	.span4
		%h2= @page.name
		%h4= @page.title
		%h4
			Last updated:
			%br
			= @page.updated_at
%br
.row
	#actions.span12
		= render "layouts/page_admin_actions/#{@page.layout}"	
= render "layouts/page_admin_templates/#{@page.layout}"
.modal-backdrop
.modal
	.modal-header
		%h3
			= @post.title
			= link_to section_page_path(@section, @page) do
				%i.icon-remove
	.modal-body
		.row-fluid
			.span12
				.thumbnail= image_tag @post.image_url(:gallery).to_s
		%br
		.row-fluid
			.span12
				= @post.content
		%br
		.row-fluid
			.span4.pull-right
				= link_to edit_section_page_post_path(@section, @page, @post) do
					%span.btn.btn-mini.btn-primary Edit
				= link_to section_page_post_path(@section, @page, @post), method: :delete, :confirm => 'Are you sure' do
					%span.btn.btn-mini.btn-danger Delete