config/routes.rb
AjoCms::Engine.routes.draw do
	root :to => "sections#index"
	match '../', :to => "ajo_cms/views#index", :as => :rails_app_root
	resources :users do
		get :first_user, :on => :collection
	end
	resources :sessions, :only => [:new, :create]
	match 'logout' => 'sessions#destroy', :as => 'logout'
	resources :companies
	resources :sections do
		collection { post :sort }
		resources :pages do
			collection { post :sort }
			resources :subsections do
				collection { post :sort }
				resources :posts do
					collection { post :sort }
				end
			end
		end
	end
	Rails.application.routes.draw do
		root :to => "ajo_cms/views#index"
		match '/:section_name/:page_name', :to => 'ajo_cms/views#section'
		match '/:section_name/:page_name/:post_id', :to => 'ajo_cms/views#post'
		match '/:section_name', :to => 'ajo_cms/views#section'
	end
	
end

app/models/ajo_cms/ajo_cms.rb
module AjoCms
  module AjoCms
    def self.table_name_prefix
      'ajo_cms_'
    end
  end
end

app/models/ajo_cms/company.rb
module AjoCms
  class Company < ActiveRecord::Base
  	attr_accessible :logo, :name, :phone, :email, :contact, :fax, :title, :address, :city, :country, :state, :zip_code, :phone, :fax, :email, :layout, :theme

  	mount_uploader :logo, LogoUploader
  end
end

app/models/ajo_cms/copy.rb
module AjoCms
  class Copy < ActiveRecord::Base
  end
end

app/models/ajo_cms/page.rb
module AjoCms
  class Page < ActiveRecord::Base
  	attr_accessible :name, :title, :layout, :section_id, :index_page, :position
  	has_many :subsections, :dependent => :destroy
  	accepts_nested_attributes_for :subsections
  	belongs_to :sections	
  	acts_as_list :scope => :section
  	default_scope order('position ASC')
  end

end

app/models/ajo_cms/post.rb
module AjoCms
  class Post < ActiveRecord::Base
  	attr_accessible :title, :content, :post_type, :subsection_id, :image, :file, :date, :crop_x, :crop_y, :crop_w, :crop_h

  	default_scope order('position ASC')

  	belongs_to :subsection
  	mount_uploader :image, ImageUploader
  	mount_uploader :file, FileUploader
    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    after_update :crop_image


    def crop_image
      image.recreate_versions! if crop_x.present?
    end

	  def next
	  	self.class.find(:first, :conditions => ["id > ? And subsection_id = ?", self.id, self.subsection_id])
	  end

	  def last
	  	self.class.find(:first, :conditions => ["id < ? And subsection_id = ?", self.id, self.subsection_id])
	  end
  end
end

app/models/ajo_cms/section.rb
module AjoCms
  class Section < ActiveRecord::Base
    attr_accessible :name, :title, :position

  	has_many :pages, :dependent => :destroy
  	accepts_nested_attributes_for :pages
  	before_create :create_index
    default_scope order('position ASC')
  	acts_as_list

  	def create_index
  		self.pages.build(:name => 'Section Page')
  		true
  	end
  end
end

app/models/ajo_cms/subsection.rb
module AjoCms
  class Subsection < ActiveRecord::Base
    attr_accessible :page_id, :position, :layout
    has_many :posts, :dependent => :destroy
    belongs_to :pages
    acts_as_list :scope => :page
  	default_scope order('position ASC')
  	
    def post_type(type)
		posts.where(:post_type => type)
    end
  end
end

app/models/ajo_cms/user.rb
module AjoCms
  class User < ActiveRecord::Base
  	has_secure_password
  	attr_accessible :email, :password, :password_confirmation
  	validates_presence_of :password, :on => :create
  end
end

app/controllers/ajo_cms/pages_controller.rb
module AjoCms
  class PagesController < ApplicationController
  	layout 'ajo_cms/admin'
  	def new
  		@section = Section.find(params[:section_id])
  		@pages = @section.pages.all
  		@page = Page.new
  	end

    def show
      @sections = Section.all
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:id])
    end

  	def edit
  		@section = Section.find(params[:section_id])
  		@pages = @section.pages.all
  		@page = Page.find(params[:id])
      @sliders = @page.posts.where(:post_type => 'slider')
  	end

    def update
      @section = Section.find(params[:section_id])
      @pages = @section.pages.all
      @page = Page.find(params[:id])

      if @page.update_attributes(params[:page])
        redirect_to section_path(@section), notice: "Page updated!"
      else
        render :action => :edit
      end
    end

    def sort
      params[:page].each_with_index do |id, index|
        Page.update_all({position: index+1}, {id: id})
      end
      render nothing: true
    end

    def create
      @page = Page.new(params[:page])
      if @page.save
        redirect_to section_path(params[:section_id]), notice: "Page added!"
      else
        render :action => "new"
      end
    end

    def destroy
      @page = Page.find(params[:id])

      @page.destroy

      redirect_to section_path(params[:section_id]), notice: "Page successfully deleted!"
    end
  end
end

app/controllers/ajo_cms/posts_controller.rb
module AjoCms
  class PostsController < ApplicationController
  	layout 'ajo_cms/admin'
    before_filter :set_defaults

    def set_defaults
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @sections = Section.all
    end
  	def new
  		@post = Post.new
  	end

    def edit
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @post = Post.find(params[:id])
    end

    def show
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @posts = @page.posts
      @post = Post.find(params[:id])
      @sliders = @page.posts.where(:post_type => 'slider')
      @headlines = @page.posts.where(:post_type => 'headlines')
      @blogs = @page.posts.where(:post_type => 'blogs')
      @images = @page.posts.where(:post_type => 'gallery')
    end


  	def create
      @sections = Section.all
  		@post = Post.new(params[:post])

  		if @post.save
        if params[:post][:image].present? && (params[:post][:post_type] == 'slider' || params[:post][:post_type == 'text'])
          render :crop
        else
          redirect_to section_page_path(params[:section_id], params[:page_id]), notice: 'Post created!'
        end
  		else
  			render 'new'
  		end
  	end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params[:post])
        redirect_to section_page_path(params[:section_id], params[:page_id], notice: 'Post updated!')
      else
        render 'edit'
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy()

      redirect_to section_page_path(params[:section_id], params[:page_id])
    end
  end
end

app/controllers/ajo_cms/users_controller.rb
module AjoCms
  class UsersController < ApplicationController
  	layout :resolve_layout
  	before_filter :authenticate, :except => :first_user

  	def index
  		@users = User.all
  	end

    def edit
      @users = User.all
      @user = User.find(params[:id])
    end

  	def new
      @users = User.all
  		@user = User.new
  	end

  	def show
  		@user = User.find(params[:id])
  	end

  	def first_user
  		@user = User.new
  	end

  	def create
  		@user = User.new(params[:user])
  		if @user.save
  			redirect_to root_url, :notice => "Signed up!"
  		else
  			render "new"
  		end
  	end

    def update
      @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
        redirect_to users_path, notice: "User updated"
      else
        render :action => :edit
      end
    end

  	private

  	def resolve_layout
  		case action_name
  		when "first_user"
  			"ajo_cms/login"
  		else
  			"ajo_cms/admin"
  		end
  	end

  end
end

app/helpers/ajo_cms/application_helper.rb
module AjoCms
  module ApplicationHelper
  	def detail_helper(label_name, field)
  		content_tag :div, :class => 'field' do
	  		content_tag(:div, label_name, :class => 'label-head') +
	  		content_tag(:div, field.empty? ? '--' : field, :class => 'detail')
	  	end
  	end
  end
end

app/helpers/ajo_cms/companies_helper.rb
module AjoCms
  module CompaniesHelper
  end
end

app/helpers/ajo_cms/pages_helper.rb
module AjoCms
  module PagesHelper
  end
end

app/helpers/ajo_cms/posts_helper.rb
module AjoCms
  module PostsHelper
  end
end

app/helpers/ajo_cms/sections_helper.rb
module AjoCms
  module SectionsHelper
  end
end

app/helpers/ajo_cms/sessions_helper.rb
module AjoCms
  module SessionsHelper
  end
end

app/helpers/ajo_cms/subsections_helper.rb
module AjoCms
  module SubsectionsHelper
  end
end

app/helpers/ajo_cms/users_helper.rb
module AjoCms
  module UsersHelper
  end
end

app/helpers/ajo_cms/views_helper.rb
module AjoCms
  module ViewsHelper
  end
end

app/views/layouts/forms/_blog.html.haml
- if params[:type] == 'blogs'
	.modal-header
		%h3
			= "#{controller.action_name.capitalize} Blog Post"
			= link_to section_page_path(@section, @page) do
				%i.icon-remove
	= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => controller.action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
		.modal-body
			.row-fluid
				.span6
					= f.hidden_field :subsection_id, :value => @subsection.id
					= f.hidden_field :post_type, :value => 'blogs'
					= f.text_field "Title", :title
					= f.text_field "Date", :date, :class => 'datepicker'
				.span6
					.field

						= f.label :image, "Image"
						= f.file_field :image
			.row-fluid
				.span12
					= f.text_area "Text", :content
		.modal-footer
			= link_to section_page_path(@section, @page) do
				%span.btn Cancel
			= f.submit "Save", :class => 'btn'

- elsif params[:type] == 'attachment'
	.modal-header
		= controller.action_name.capitalize + ' Attachment'
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
	= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
		.modal-body
			.row-fluid
				.span6
					= f.hidden_field :subsection_id, :value => @subsection.id
					= f.hidden_field :post_type, :value => 'attachment'
					= f.text_field "Label", :title
				.span6
					= f.label "File"
					= f.file_field :file
		.modal-footer
			= link_to section_page_path(@section, @page) do
				%span.btn Cancel
			= f.submit "Save", :class => 'btn'

- elsif params[:type] == 'headline'
	.modal-header
		%h3
			= controller.action_name.capitalize + ' Headline'
			= link_to section_page_path(@section, @page) do
				%i.icon-remove
	= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
		.modal-body
			.row-fluid
				.span12
					= f.hidden_field :subsection_id, :value => @subsection.id
					= f.hidden_field :post_type, :value => 'headline'
					= f.text_field "Title", :title
			.row-fluid
				.span12
					= f.text_area "Copy", :content
		.modal-footer
			= link_to section_page_path(@section, @page) do
				%span.btn Cancel
			= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_columns.html.haml
.modal-header
	%h3
		= controller.action_name.capitalize + ' Column'
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
	.modal-body
		.row-fluid
			.span12
				= f.hidden_field :subsection_id, :value => @subsection.id
				= f.hidden_field :post_type, :value => 'text'
				= f.text_field "Title", :title
		.row-fluid
			.span12
				= f.text_area "Copy", :content
	.modal-footer
		= link_to section_page_path(@section, @page) do
			%span.btn Cancel
		= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_contact.html.haml
.modal-header
	%h3
		New Slider Image
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => section_page_posts_path(@section, @page, @post) do |f|
	.modal-body
		.row-fluid
			.span6
				= f.hidden_field :page_id, :value => @page.id
				= f.hidden_field :post_type, :value => 'slider'
				= f.text_field "Title", :title
			.span6
				.field
					= f.label :image, "Image"
					= f.file_field :image
		.row-fluid
			.span12
				= f.text_area "Caption", :content
	.modal-footer
		= link_to section_page_path(@section, @page) do
			%span.btn Cancel
		= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_contacts.html.haml
.modal-header
	%h3
		New Contact
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => controller.action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
	.modal-body
		.row-fluid
			.span6
				= f.hidden_field :subsection_id, :value => @subsection.id
				= f.hidden_field :post_type, :value => 'contacts'
				= f.text_field "Name", :title
			.span6
				.field
					= f.label :image, "Image"
					= f.file_field :image
		.row-fluid
			.span12
				= f.text_area "Description", :content
	.modal-footer
		= link_to section_page_path(@section, @page) do
			%span.btn Cancel
		= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_gallery.html.haml
.modal-header
	%h3
		New Gallery Image
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => controller.action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
	.modal-body
		.row-fluid
			.span6
				= f.hidden_field :subsection_id, :value => @subsection.id
				= f.hidden_field :post_type, :value => 'gallery'
				= f.text_field "Title", :title
			.span6
				.field
					= f.label :image, "Image"
					= f.file_field :image
		.row-fluid
			.span12
				= f.text_area "Caption", :content
	.modal-footer
		= link_to section_page_path(@section, @page) do
			%span.btn Cancel
		= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_slider.html.haml
- if params[:type] == 'slider'
	.modal-header
		%h3
			= controller.action_name.capitalize + ' Slider Image'
			= link_to section_page_path(@section, @page) do
				%i.icon-remove
	= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => controller.action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
		.modal-body
			.row-fluid
				.span6
					= f.hidden_field :subsection_id, :value => @subsection.id
					= f.hidden_field :post_type, :value => 'slider'
					= f.text_field "Title", :title
				.span6
					.field
						= f.label :image, "Image"
						= f.file_field :image
			.row-fluid
				.span12
					= f.text_area "Caption", :content
		.modal-footer
			= link_to section_page_path(@section, @page) do
				%span.btn Cancel
			= f.submit "Save", :class => 'btn'
- elsif params[:type] == 'headline'
	.modal-header
		%h3
			= controller.action_name.capitalize + ' Headline'
			= link_to section_page_path(@section, @page) do
				%i.icon-remove
	= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @post) : section_page_post_path(@section, @page, @post) do |f|
		.modal-body
			.row-fluid
				.span12
					= f.hidden_field :page_id, :value => @page.id
					= f.hidden_field :post_type, :value => 'headline'
					= f.text_field "Title", :title
			.row-fluid
				.span12
					= f.text_area "Copy", :content
		.modal-footer
			= link_to section_page_path(@section, @page) do
				%span.btn Cancel
			= f.submit "Save", :class => 'btn'

app/views/layouts/forms/_text.html.haml
.modal-header
	%h3
		= controller.action_name.capitalize + ' Text'
		= link_to section_page_path(@section, @page) do
			%i.icon-remove
= form_for @post, builder: LabelledFormBuilder, :html => {:multipart => true}, :url => action_name == 'new' ? section_page_subsection_posts_path(@section, @page, @subsection, @post) : section_page_subsection_post_path(@section, @page, @subsection, @post) do |f|
	.modal-body
		.row-fluid
			.span12
				= f.hidden_field :subsection_id, :value => @subsection.id
				= f.hidden_field :post_type, :value => 'text'
				= f.text_field "Title", :title
		.row-fluid
			.span12
				= f.text_area "Copy", :content
	.modal-footer
		= link_to section_page_path(@section, @page) do
			%span.btn Cancel
		= f.submit "Save", :class => 'btn'

app/views/layouts/main_templates/_default.html.haml
.default-layout.wrapper{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
	.container
		#header
			.container
				.row-fluid
					.span12
						= image_tag AjoCms::Company.first.logo_url.to_s
				.container
					#subheader
						.row
							.navbar.span12
								%ul.nav.nav-bar
									- @sections.each do |section|
										%li.dropdown
											- if controller.action_name == 'index'
												= link_to section.name, "/#{section.name}/#{@page.name}", :class => 'dropdown-toggle', 'data-dropdown' => 'dropdown'
												-if section.pages.count > 1
													%ul.dropdown-menu
														-section.pages[1..-1].each do |page|
															%li= link_to page.name, "/#{section.name}/#{page.name}"
											- else
												= link_to section.name, "/#{section.name}", :class => 'dropdown-toggle', 'data-dropdown' => 'dropdown'
												- if section.pages.count > 1
													%ul.dropdown-menu
														-section.pages[1..-1].each do |page|
															%li= link_to page.name, "/#{section.name}/#{page.name}"
	#content.container
		#innercontent
			- @subsections.each do |sub|
				= render :partial => 'layouts/page_templates/' + (sub.layout.nil? ? 'default' : sub.layout), :locals => {:subsection => sub}
			.default-layout{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
				.container
					.footer.rounded
						#info.container
							.row-fluid
								.span4
									= @company.name
								.span5
									= @company.address + ' ' +@company.city + ' ' + (@company.province || '') + ' ' + (@company.zip_code || '')
								.span3
									.row-fluid
										.span4
										.span8
											Phone:
											= @company.phone
							-#.row-fluid
							-#	.span12
							-#		- @sections.each_slice(6) do |slice|
							-#			.row-fluid
							-#				- slice.each do |section|
							-#					.section_map.span2
							-#						=section.name
							-#						%ul.page_map
							-#							- section.pages[1..-1].each do |page|
							-#								%li= page.name
			%br

app/views/layouts/main_templates/_header.html.haml
.wrapper{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
	#header
		.container
			.row-fluid
				.span12
					= image_tag AjoCms::Company.first.logo_url.to_s
		#subheader
			.container
				.row-fluid
					.navbar.span12
						%ul.nav.nav-bar
							- @sections.each do |section|
								%li.dropdown
									- if controller.action_name == 'index'
										= link_to section.name, "/#{section.name}/#{@page.name}", :class => 'dropdown-toggle', 'data-dropdown' => 'dropdown'
										-if section.pages.count > 1
											%ul.dropdown-menu
												-section.pages[1..-1].each do |page|
													%li= link_to page.name, "/#{section.name}/#{page.name}"
									- else
										= link_to section.name, "/#{section.name}", :class => 'dropdown-toggle', 'data-dropdown' => 'dropdown'
										- if section.pages.count > 1
											%ul.dropdown-menu
												-section.pages[1..-1].each do |page|
													%li= link_to page.name, "/#{section.name}/#{page.name}"
		.spacer
	#content.container
		= render 'layouts/page_templates/' + @page_layout
	.push
%div{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
	.spacer
	.footer
		#info.container
			.row-fluid
				.span3
					= @company.name
				.span5
					= @company.address + ', ' + @company.city + ', ' + @company.state + ', ' + @company.	country + ' ' + @company.zip_code
				.span2
					Phone: 
					= @company.phone
				.span2
					%a{:href => "mailto: #{@company.email}"}= @company.email
				%br
				%br
			.row-fluid
				.span12
					- @sections.each_slice(@sections.count) do |slice|
						.row-fluid
							- slice.each do |section|
								.section_map{:style => "min-width: #{80/@sections.count}%; max-width: #{105/(@sections.count)}%; display: inline-block; float: left; padding-right: 20px"}
									= link_to section.name, "/#{section.name}/#{@section.pages.first.name}"
									%br
									- if section.pages.count > 0	
										%ul.page_map
											- section.pages[1..-1].each do |page|
												%li= link_to page.name, "/#{section.name}/#{page.name}"

			

app/views/layouts/main_templates/_sidebar.html.haml
.wrapper{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
	#header
		.container
			.row-fluid
				.span12
					= image_tag AjoCms::Company.first.logo_url.to_s
	.spacer
	#content.container
		.row-fluid
			.span2
				#sidenav
					%ul.nav
						- @sections.each do |section|
							%li
								= link_to section.name, "/#{section.name}/#{@page.name}", :class => 'dropdown-toggle', 'data-dropdown' => 'dropdown'
								- if @section.name.capitalize == section.name && @section.pages.count > 1
									%ul.nav.sub
										- @section.pages[1..-1].each do |page|
											%li.sub= page.name
			.span10
				= render 'layouts/page_templates/' + @page_layout
	.push
%div{:class => AjoCms::Company.first.theme.nil? ? 'default' : AjoCms::Company.first.theme }
	.footer
		#info.container
			.row-fluid
				.span8
					- @sections.each_slice(2) do |slice|
						.row-fluid
							- slice.each do |section|
								.section_map.span6
									%h4
										=section.name
									%ul.page_map
										- section.pages[1..-1].each do |page|
											%li= page.name

				.span4
					.row-fluid
						.span12
							%h4= @company.name
					%br
					.row-fluid
						.span6
							%b Contact: 
							%br
							= @company.contact
						.span6
							%b Email:
							= @company.email
				.span2

app/views/layouts/page_admin_actions/_blog.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'blogs') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_columns.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'columns') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_contact.html.haml
%br
%br
= link_to edit_section_page_subsection_path(@section, @page, subsection) do
	%span.btn
		%i.icon-edit
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_contacts.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'contacts') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_gallery.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'gallery') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_slider.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'slider') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_admin_actions/_text.html.haml
%br
%br
= link_to new_section_page_subsection_post_path(@section, @page, subsection, :type => 'headline') do
	%span.btn
		%i.icon-plus
= link_to section_page_subsection_path(@section, @page, subsection), :method => 'delete', :confirm => 'Are you sure?' do
	%span.btn
		%i.icon-remove
%span.btn
	%i.icon-move
%br
%br

app/views/layouts/page_templates/_blog.html.haml
.blog.innercontainer
	%br
	- subsection.posts.each do |post|
		.entry
			.row-fluid
				.entry-head.row-fluid
					%h3= post.title
					- if post.date?
						%h4= post.date
				.entry-content.row-fluid
					- if post.image_url(:thumb).to_s != ''
						.span9
							= post.content.nil? ? post.content : post.content.html_safe
							
						.span3
							= image_tag post.image_url.to_s
					- else
						.span12
							= post.content.nil? ? post.content : post.content.html_safe

app/views/layouts/page_templates/_columns.html.haml
.columns
	.innercontainer
		- subsection.posts.each_slice(3) do |slice|
			.row-fluid
				- slice.each do |post|
					.span4.text-column
						%p
							%h3
								= post.title
							%br
							= post.content.html_safe
		%br

app/views/layouts/page_templates/_contacts.html.haml
.contacts.innercontainer
	%br
	- subsection.posts.each do |post|
		.row-fluid
			.span12
				.row-fluid
					.span12
						%h3= post.title
				.row-fluid
					-if !post.image_url(:large).nil?
						.span7
							.thumbnail
								= image_tag post.image_url(:large).to_s
						.span5
							= post.content.nil? ? post.content : post.content.html_safe
					- else
						.span12
							= post.content.nil? ? post.content : post.content.html_safe

app/views/layouts/page_templates/_default.html.haml
More coming soon!