config/routes.rb
AjoCms::Engine.routes.draw do
	root :to => "sections#index"
	match '../', :to => "ajo_cms/views#index", :as => :rails_app_root
	resources :users do
		get :first_user, :on => :collection
	end
	resources :sessions, :only => [:new, :create]
	match 'logout' => 'sessions#destroy', :as => 'logout'
	resources :companies
	resources :sections do
		collection { post :sort }
		resources :pages do
			collection { post :sort }
			resources :subsections do
				collection { post :sort }
				resources :posts do
					collection { post :sort }
				end
			end
		end
	end
	Rails.application.routes.draw do
		root :to => "ajo_cms/views#index"
		match '/:section_name/:page_name', :to => 'ajo_cms/views#section'
		match '/:section_name/:page_name/:post_id', :to => 'ajo_cms/views#post'
		match '/:section_name', :to => 'ajo_cms/views#section'
	end
	
end

app/models/ajo_cms/ajo_cms.rb
module AjoCms
  module AjoCms
    def self.table_name_prefix
      'ajo_cms_'
    end
  end
end

app/models/ajo_cms/company.rb
module AjoCms
  class Company < ActiveRecord::Base
  	attr_accessible :logo, :name, :phone, :email, :contact, :fax, :title, :address, :city, :country, :state, :zip_code, :phone, :fax, :email, :layout, :theme

  	mount_uploader :logo, LogoUploader
  end
end

app/models/ajo_cms/copy.rb
module AjoCms
  class Copy < ActiveRecord::Base
  end
end

app/models/ajo_cms/page.rb
module AjoCms
  class Page < ActiveRecord::Base
  	attr_accessible :name, :title, :layout, :section_id, :index_page, :position
  	has_many :subsections, :dependent => :destroy
  	accepts_nested_attributes_for :subsections
  	belongs_to :sections	
  	acts_as_list :scope => :section
  	default_scope order('position ASC')
  end

end

app/models/ajo_cms/post.rb
module AjoCms
  class Post < ActiveRecord::Base
  	attr_accessible :title, :content, :post_type, :subsection_id, :image, :file, :date, :crop_x, :crop_y, :crop_w, :crop_h

  	default_scope order('position ASC')

  	belongs_to :subsection
  	mount_uploader :image, ImageUploader
  	mount_uploader :file, FileUploader
    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    after_update :crop_image


    def crop_image
      image.recreate_versions! if crop_x.present?
    end

	  def next
	  	self.class.find(:first, :conditions => ["id > ? And subsection_id = ?", self.id, self.subsection_id])
	  end

	  def last
	  	self.class.find(:first, :conditions => ["id < ? And subsection_id = ?", self.id, self.subsection_id])
	  end
  end
end

app/models/ajo_cms/section.rb
module AjoCms
  class Section < ActiveRecord::Base
    attr_accessible :name, :title, :position

  	has_many :pages, :dependent => :destroy
  	accepts_nested_attributes_for :pages
  	before_create :create_index
    default_scope order('position ASC')
  	acts_as_list

  	def create_index
  		self.pages.build(:name => 'Section Page')
  		true
  	end
  end
end

app/models/ajo_cms/subsection.rb
module AjoCms
  class Subsection < ActiveRecord::Base
    attr_accessible :page_id, :position, :layout
    has_many :posts, :dependent => :destroy
    belongs_to :pages
    acts_as_list :scope => :page
  	default_scope order('position ASC')
  	
    def post_type(type)
		posts.where(:post_type => type)
    end
  end
end

app/models/ajo_cms/user.rb
module AjoCms
  class User < ActiveRecord::Base
  	has_secure_password
  	attr_accessible :email, :password, :password_confirmation
  	validates_presence_of :password, :on => :create
  end
end

app/controllers/ajo_cms/application_controller.rb
module AjoCms
  class ApplicationController < ActionController::Base
  	before_filter :first_user
  	before_filter :current_user
  	before_filter :authenticate, :except => :users
  	@@company = Company.first

  	

  	private
	
	def authenticate
		unless @current_user || User.count < 1
			redirect_to new_session_path
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def first_user
		if User.count < 1
			redirect_to first_user_users_path
		end
	end

	

	helper_method :current_user, :first_user
  end
end

app/controllers/ajo_cms/companies_controller.rb
module AjoCms
  class CompaniesController < ApplicationController
  	layout 'ajo_cms/admin'
	def show
  		@company = Company.first
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])

		if @company.update_attributes(params[:company])
			redirect_to company_path(@company), notice: "Settings Updated"
		else
			render :action => :edit
		end
	end
  end
end

app/controllers/ajo_cms/pages_controller.rb
module AjoCms
  class PagesController < ApplicationController
  	layout 'ajo_cms/admin'
  	def new
  		@section = Section.find(params[:section_id])
  		@pages = @section.pages.all
  		@page = Page.new
  	end

    def show
      @sections = Section.all
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:id])
    end

  	def edit
  		@section = Section.find(params[:section_id])
  		@pages = @section.pages.all
  		@page = Page.find(params[:id])
      @sliders = @page.posts.where(:post_type => 'slider')
  	end

    def update
      @section = Section.find(params[:section_id])
      @pages = @section.pages.all
      @page = Page.find(params[:id])

      if @page.update_attributes(params[:page])
        redirect_to section_path(@section), notice: "Page updated!"
      else
        render :action => :edit
      end
    end

    def sort
      params[:page].each_with_index do |id, index|
        Page.update_all({position: index+1}, {id: id})
      end
      render nothing: true
    end

    def create
      @page = Page.new(params[:page])
      if @page.save
        redirect_to section_path(params[:section_id]), notice: "Page added!"
      else
        render :action => "new"
      end
    end

    def destroy
      @page = Page.find(params[:id])

      @page.destroy

      redirect_to section_path(params[:section_id]), notice: "Page successfully deleted!"
    end
  end
end

app/controllers/ajo_cms/posts_controller.rb
module AjoCms
  class PostsController < ApplicationController
  	layout 'ajo_cms/admin'
    before_filter :set_defaults

    def set_defaults
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @sections = Section.all
    end
  	def new
  		@post = Post.new
  	end

    def edit
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.find(params[:subsection_id])
      @post = Post.find(params[:id])
    end

    def show
      @section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @posts = @page.posts
      @post = Post.find(params[:id])
      @sliders = @page.posts.where(:post_type => 'slider')
      @headlines = @page.posts.where(:post_type => 'headlines')
      @blogs = @page.posts.where(:post_type => 'blogs')
      @images = @page.posts.where(:post_type => 'gallery')
    end


  	def create
      @sections = Section.all
  		@post = Post.new(params[:post])

  		if @post.save
        if params[:post][:image].present? && (params[:post][:post_type] == 'slider' || params[:post][:post_type == 'text'])
          render :crop
        else
          redirect_to section_page_path(params[:section_id], params[:page_id]), notice: 'Post created!'
        end
  		else
  			render 'new'
  		end
  	end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params[:post])
        redirect_to section_page_path(params[:section_id], params[:page_id], notice: 'Post updated!')
      else
        render 'edit'
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy()

      redirect_to section_page_path(params[:section_id], params[:page_id])
    end
  end
end

app/controllers/ajo_cms/sections_controller.rb
module AjoCms
  class SectionsController < ApplicationController
    layout 'ajo_cms/admin'
  	def index
  		@sections = Section.order(:position)
  	end

  	def new
  		@sections = Section.all
  		@section = Section.new
  	end

  	def show
      @sections = Section.all
  		@section = Section.find(params[:id])
  		@pages = @section.pages.all
  	end

  	def edit
  		@sections = Section.all
  		@section = Section.find(params[:id])
  	end

  	def create
  		@section = Section.new(params[:section])

  		if @section.save
  			redirect_to sections_path, notice: "Section created!"
  		else
  			render :action => "new"
  		end
  	end

    def sort
      params[:section].each_with_index do |id, index|
        Section.update_all({position: index+1}, {id: id})
      end
      render nothing: true
    end

  	def update
  		@section = Section.find(params[:id])
  		if @section.update_attributes(params[:section])
  			redirect_to sections_path, notice: "Section updated!"
  		else
  			render :action => "edit"
  		end
  	end

  	def destroy
  		@section = Section.find(params[:id])
  		@section.destroy

  		redirect_to sections_path, notice: "Section deleted!"
  	end
  end
end

app/controllers/ajo_cms/sessions_controller.rb
module AjoCms
  class SessionsController < ApplicationController
  	skip_before_filter :authenticate
    layout 'ajo_cms/login'
  	def new
  	end

  	def create
  		user = User.find_by_email(params[:email])
  		if user && user.authenticate(params[:password])
  			session[:user_id] = user.id
  			redirect_to root_url, :notice => "Logged in!"
  		else
  			flash.now.alert = "Invalid email or password"
  			render "new"
  		end
  	end

    def destroy
      session[:user_id] = nil
      redirect_to new_session_path, :notice => "Logged out!"
    end
  end
end

app/controllers/ajo_cms/subsections_controller.rb
module AjoCms
  class SubsectionsController < ApplicationController
  	layout 'ajo_cms/admin'
  	def new
      @sections = Section.all
  		@section = Section.find(params[:section_id])
      @page = Page.find(params[:page_id])
      @subsection = Subsection.new
  	end
  	def create
  		@section = Section.find(params[:section_id])
  		@page = Page.find(params[:page_id])
  		@subsection = Subsection.new(params[:subsection])
  		if @subsection.save
  			redirect_to section_page_path(@section, @page), notice: 'Subsection created'
  		else
  			render 'new'
  		end
  	end
    def destroy
      @subsection = Subsection.find(params[:id])
      @subsection.destroy()

      redirect_to section_page_path(params[:section_id], params[:page_id])
    end
    def sort
      params[:page].each_with_index do |id, index|
        Page.update_all({position: index+1}, {id: id})
      end
      render nothing: true
    end
  end
end

app/controllers/ajo_cms/users_controller.rb
module AjoCms
  class UsersController < ApplicationController
  	layout :resolve_layout
  	before_filter :authenticate, :except => :first_user

  	def index
  		@users = User.all
  	end

    def edit
      @users = User.all
      @user = User.find(params[:id])
    end

  	def new
      @users = User.all
  		@user = User.new
  	end

  	def show
  		@user = User.find(params[:id])
  	end

  	def first_user
  		@user = User.new
  	end

  	def create
  		@user = User.new(params[:user])
  		if @user.save
  			redirect_to root_url, :notice => "Signed up!"
  		else
  			render "new"
  		end
  	end

    def update
      @user = User.find(params[:id])

      if @user.update_attributes(params[:user])
        redirect_to users_path, notice: "User updated"
      else
        render :action => :edit
      end
    end

  	private

  	def resolve_layout
  		case action_name
  		when "first_user"
  			"ajo_cms/login"
  		else
  			"ajo_cms/admin"
  		end
  	end

  end
end

app/controllers/ajo_cms/views_controller.rb
module AjoCms
  class ViewsController < ApplicationController
    skip_before_filter :authenticate
    before_filter :set_defaults
  	layout 'ajo_cms/public'
    
    def set_defaults
      @site_layout = Company.first.layout.nil? ? 'default' : Company.first.layout
      @company = Company.first
      @sections = Section.order('position')
    end
    
  	def index
  		@section = Section.first
  		@page = @section.pages.first
      @subsections = @page.subsections
  	end

  	def section
  		@section = Section.where(:name => params[:section_name]).first
      if params[:page_name]
        @page = @section.pages.where(:name => params[:page_name]).first
      else
        @page = @section.pages.first
      end
      @subsections = @page.subsections
  	end

    def post
      @section = Section.where(:name => params[:section_name]).first
      @page = params[:page_name].nil? ? @section.pages.first : @section.pages.where(:name => params[:page_name]).first
      @subsections = @page.subsections
      @post = Post.find(params[:post_id])
    end
  end
end

app/helpers/ajo_cms/application_helper.rb
module AjoCms
  module ApplicationHelper
  	def detail_helper(label_name, field)
  		content_tag :div, :class => 'field' do
	  		content_tag(:div, label_name, :class => 'label-head') +
	  		content_tag(:div, field.empty? ? '--' : field, :class => 'detail')
	  	end
  	end
  end
end

app/helpers/ajo_cms/companies_helper.rb
module AjoCms
  module CompaniesHelper
  end
end

app/helpers/ajo_cms/pages_helper.rb
module AjoCms
  module PagesHelper
  end
end

app/views/ajo_cms/pages/_sections_table.html.haml
#accordion
	- @sections.each_with_index do |section, index|
		%h3= section.name
		%div
			%ul.nav
				- section.pages.each do |page|
					%li= link_to page.name, section_page_path(section, page)
		- if @section.id == section.id
			- @index = index
:javascript
	$('#accordion').accordion({
		'active' : #{@index},
		collapsible: true,
		autoHeight: true
	})

app/views/ajo_cms/pages/edit.html.haml
%h2=@section.name
%h5
	= @section.title

%table.table.table-striped
	%thead
		%tr
			%th Page
			%th Title
			%th Layout
			%th
			%th
	%tbody
		- @pages.each do |page|
			%tr
				%td= page.name
				%td= page.title
				%td= page.layout
				%td= page.index_page == true ? 'index' : ''
				%td.links
					= link_to edit_section_page_path(@section, page) do
						%i.icon-edit
					= link_to section_page_path(@section, page), method: :delete, :confirm => 'Are you sure?' do
						%i.icon-trash
.modal-backdrop
.modal
	.modal-header
		%h3
			Edit Page
			= link_to section_path(@section) do
				%i.icon-remove
	= form_for @page, :builder => LabelledFormBuilder, :url => section_page_path(@section, @page) do |f|
		.modal-body
			= f.hidden_field :section_id, :value => @section.id
			.row-fluid
				.span6= f.text_field "Name", :name
				.span6= f.text_field "Title", :title
			%b Layout
			%br
			%br
			.row-fluid
				- ['slider', 'text', 'gallery'].each do |layout|
					.span4
						= radio_button_tag 'page[layout]', layout, @page.layout == layout
						= layout.capitalize
						.thumbnail= image_tag("ajo_cms/page_#{layout}.png")
			%br
			.row-fluid
				- ['contacts', 'contact', 'blog'].each do |layout|
					.span4
						= radio_button_tag 'page[layout]', layout, @page.layout == layout
						= layout.capitalize
						.thumbnail= image_tag("ajo_cms/page_#{layout}.png")
			%br
			.row-fluid
				- ['calendar'].each do |layout|
					.span4
						= radio_button_tag 'page[layout]', layout, @page.layout == layout
						= layout.capitalize
						.thumbnail= image_tag("ajo_cms/page_#{layout}.png")
		.modal-footer
			= link_to section_path(@section) do
				%span.btn Cancel
			= f.submit 'Save', :class => 'btn'

app/views/ajo_cms/pages/new.html.haml
%h2=@section.name
%h5
	= @section.title

%table.table.table-striped
	%thead
		%tr
			%th Page
			%th Title
			%th Layout
			%th
			%th
	%tbody
		- @pages.each do |page|
			%tr
				%td= page.name
				%td= page.title
				%td= page.layout
				%td= page.index_page == true ? 'index' : ''
				%td.links
					= link_to edit_section_page_path(@section, page) do
						%i.icon-edit
					= link_to section_page_path(@section, page), method: :delete, :confirm => 'Are you sure?' do
						%i.icon-trash
.modal-backdrop
.modal
	.modal-header
		%h3
			New Page
			= link_to section_path(@section) do
				%i.icon-remove
	= form_for @page, :builder => LabelledFormBuilder, :url => section_pages_path do |f|
		.modal-body
			= f.hidden_field :section_id, :value => @section.id
			.row-fluid
				.span6= f.text_field "Name", :name
				.span6= f.text_field "Title", :title
			%b Layout
			%br
			%br
			.row-fluid
				- ['slider', 'text', 'gallery'].each do |layout|
					.span4
						= radio_button_tag 'page[layout]', layout, @page.layout == layout
						= layout.capitalize
						.thumbnail= image_tag("ajo_cms/page_#{layout}.png")
			%br
			.row-fluid
				- ['contacts', 'contact', 'blog'].each do |layout|
					.span4
						= radio_button_tag 'page[layout]', layout, @page.layout == layout
						= layout.capitalize
						.thumbnail= image_tag("ajo_cms/page_#{layout}.png")
		.modal-footer
			= link_to section_path(@section) do
				%span.btn Cancel
			= f.submit 'Save', :class => 'btn'

app/views/ajo_cms/pages/show.html.haml
.row-fluid
	.span2
		.row-fluid
			.span12
				= render 'sections_table'
	.span10
		- if @page.subsections.count == 0
			.alert.alert-info
				Add a subsection (right hand side) to get started!
		- @page.subsections.each do |sub|
			.row-fluid
				.span2
					= image_tag "ajo_cms/page_#{sub.layout}.png", :height => '100px'
					= render :partial => "layouts/page_admin_actions/#{sub.layout}", :locals => {:subsection => sub}	
				.span10
					.row-fluid
					= render :partial => "layouts/page_admin_templates/#{sub.layout}", :locals => {:subsection => sub}